"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import LoginPage from "@/app/(auth)/login/page";
import Modal from "@/components/core/Modal";
import Footer from "@/components/layouts/Footer";
import { useLoginModal } from "@/store/useLoginModal";
import Navbar from "./navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const disableNavbar = ["/register"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isOpen, onClose } = useLoginModal(); // status modal
  // const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex flex-col min-h-screen`}
      >
        <SessionProvider>
          {/* {!disableNavbar.includes(pathname) && <Navbar />} */}
          <Navbar />

          <main className="grow bg-white">{children}</main>

          <Footer />

          <Modal isOpen={isOpen} onClose={onClose}>
            <LoginPage />
          </Modal>
        </SessionProvider>
      </body>
    </html>
  );
}
